find_package(Boost 1.68.0 REQUIRED system)
find_package(RapidJSON REQUIRED)
if(NOT TARGET RapidJSON::RapidJSON)
  add_library(RapidJSON::RapidJSON INTERFACE IMPORTED)
  set_target_properties(RapidJSON::RapidJSON PROPERTIES INTERFACE_INCLUDE_DIRECTORIES ${RapidJSON_INCLUDE_DIRS})
endif()
find_package(OpenSSL REQUIRED)
find_package(Sockets REQUIRED)
find_package(Threads REQUIRED)
find_package(ZLIB REQUIRED)
